import{a as P,S as q,i as c}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const $="56476616-0d0640f868639d933d3cc2b11",E="https://pixabay.com/api/";async function m(t,r){const n=new URLSearchParams({key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:"15"});return(await P.get(`${E}?${n}`)).data}const l=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function B(){l&&(l.innerHTML="")}function g(t){if(!l)return;const r=t.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:s,comments:S,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${n}" alt="${e}" />
          </a>
          <div class="info-block">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${s}</p>
            <p><b>Comments:</b> ${S}</p>
            <p><b>Downloads:</b> ${v}</p>
          </div>
        </li>
      `).join("");l.insertAdjacentHTML("beforeend",r),M.refresh()}function p(){d&&d.classList.remove("is-hidden")}function y(){d&&d.classList.add("is-hidden")}function b(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}const R=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let h="",a=1;const L=15;R.addEventListener("submit",H);O.addEventListener("click",N);async function H(t){t.preventDefault();const r=t.currentTarget.elements.query.value.trim();if(r===""){c.warning({title:"Warning",message:"Search field cannot be empty!",position:"topRight"});return}h=r,a=1,B(),f(),p();try{const n=await m(h,a);if(n.hits.length===0){c.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(n.hits),n.totalHits>L&&b()}catch{w()}finally{y()}t.currentTarget.reset()}async function N(){a+=1,f(),p();try{const t=await m(h,a);g(t.hits),T();const r=Math.ceil(t.totalHits/L);a>=r?(f(),c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{w()}finally{y()}}function T(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}function w(){c.error({title:"Error",message:"Something went wrong with the server fetching.",position:"topRight"})}
//# sourceMappingURL=index.js.map
